ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    # TF
    publish_tf: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Wheel odometry
    odometry0: /diff_cont/odom
    odometry0_config: [true,  true,  false,  # x, y, z
                       false, false, false,  # roll, pitch, yaw
                       true,  true,  false,  # vx, vy, vz
                       false, false, false]  # vroll, vpitch, vyaw
    odometry0_differential: false

    # IMU
    imu0: /imu/data
    imu0_config: [false, false, false,  # x, y, z
                  true,  true,  true,   # roll, pitch, yaw
                  false, false, false, # vx, vy, vz
                  true,  true,  true]  # vroll, vpitch, vyaw
    imu0_differential: true
    imu0_remove_gravitational_acceleration: true